### ISSUE TITLE
Remove styling for `(.Calendar__footer) button`

### ISSUE THREAD

**Issue by rusakovic** [Kiarash-Z/react-modern-calendar-datepicker#165] opened 2020-06-30 15:02 UTC
Hello
Thank you for your library.
Could you, please, remove styling for footer to implement own component?

`.Calendar *:not(.Calendar__footer) button {
  font-family: inherit;
  background: transparent;
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  outline: none;
}`

**Comment by Kiarash-Z** [comment] 2020-07-01 20:19
Hi, I'm not sure If I understand you question properly, but this style **does not include footer button**. I've used CSS [:not ](https://developer.mozilla.org/en-US/docs/Web/CSS/:not#:~:text=The%20%3Anot()%20CSS%20pseudo,as%20the%20negation%20pseudo%2Dclass) selector to exclude the calendar general styles for the footer.

**Comment by rusakovic** [comment] 2020-07-02 08:56
Hello.
Please, check it


![image](https://user-images.githubusercontent.com/17801144/86338395-f911e700-bc5a-11ea-94d8-bc90877ccff3.png)
vs
![image](https://user-images.githubusercontent.com/17801144/86338424-0038f500-bc5b-11ea-8163-9b282013df67.png)

**Comment by Kiarash-Z** [comment] 2020-07-02 10:51
This is so weird! Can you provide a simple example on [CodeSandbox](https://codesandbox.io/), please?

**Comment by rusakovic** [comment] 2020-07-02 12:41
It's a private repository.
But, I used <Button /> .tsx component. 
In your docs - used inline `div`s
Maybe it's an issue

**Comment by Kiarash-Z** [comment] 2020-07-02 19:49
I didn't ask for the entire repo. You can just reproduce the date picker part with different actions in CodeSandbox. I just tested the styles and they worked just fine. Maybe you're transforming CSS classes, therefore, styles can't find any `div` with `Calendar__footer` class. Anyway, I think the fix is quite easy. You just need to apply a CSS style with higher specificity using `!important`

**Comment by rusakovic** [comment] 2020-07-03 05:57
Hello.
Thank you.
But using `!important` is a bad practice.
Current structure is:
![image](https://user-images.githubusercontent.com/17801144/86436508-11413f00-bd0b-11ea-9bd6-86c2a366e7a6.png)

Why not to remove `.Calendar *:not(.Calendar__footer) button` ? Each developer could create their own component and style?

**Comment by Kiarash-Z** [comment] 2020-07-03 13:25
> Why not to remove .Calendar *:not(.Calendar__footer) button ? Each developer could create their own component and style?

Exactly! that's the point of using the `:not` to **exclude** buttons inserted by developer in the calendar footer. But, I figured out why it's not applying in this case. It looks like it doesn't work with nested buttons. If your button is a direct child of the calendar footer, it would work. I'm working on a fix for this

**Comment by rusakovic** [comment] 2020-07-03 13:28
Great. Thank you!
Will be very helpful!

also, in your docs
`  // Return a { year: number, month: number, day: number } object
  getToday(gregorianTodayObject: any) {
    return gregorianTodayObject;
  },
`

Should be `gregorian` calendar.

**Comment by Kiarash-Z** [comment] 2020-07-03 14:21
This is now fixed in the latest version 3.1.6 🎉 For the documentation issue, can you open a dedicated issue and explain this further, please?

**Comment by rusakovic** [comment] 2020-07-03 15:21
Thank you!

**Closed** 2020-07-03 15:50 UTC
Labels: bug, discussion
