### ISSUE TITLE
How can I choose the exact time? 

### ISSUE THREAD

**Issue by sh4msi** [Kiarash-Z/react-modern-calendar-datepicker#41] opened 2019-10-16 13:19 UTC
hi
How can I choose the exact time?  (Hours and minutes)

**Comment by thebrodmann** [comment] 2019-10-16 18:21
Duplicate of #25

**Comment by Kiarash-Z** [comment] 2019-10-19 05:42
Hi,
This package is a date picker, not a time picker. Yet, I would consider adding this feature

**Closed** 2019-10-25 15:40 UTC
